/*
MPCCcar : A fast customized optimization solver.

Copyright (C) 2013-2020 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCES PRO v4.1.1 on Monday, February 1, 2021 at 9:26:33 PM */

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif

#ifndef MPCCcar_H
#define MPCCcar_H

#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double MPCCcar_float;

typedef double MPCCcarinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_MPCCcar
#define MISRA_C_MPCCcar (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_MPCCcar
#define RESTRICT_CODE_MPCCcar (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_MPCCcar
#define SET_PRINTLEVEL_MPCCcar    (0)
#endif

/* timing */
#ifndef SET_TIMING_MPCCcar
#define SET_TIMING_MPCCcar    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_MPCCcar			(200)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_MPCCcar		(MPCCcar_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_MPCCcar	(200) 

/* maximum number of supported elements in the filter */
#define MAX_SOC_IT_MPCCcar			(4) 

/* desired relative duality gap */
#define SET_ACC_RDGAP_MPCCcar		(MPCCcar_float)(0.0001)

/* desired maximum residual on equality constraints */
#define SET_ACC_RESEQ_MPCCcar		(MPCCcar_float)(1E-06)

/* desired maximum residual on inequality constraints */
#define SET_ACC_RESINEQ_MPCCcar	(MPCCcar_float)(1E-06)

/* desired maximum violation of complementarity */
#define SET_ACC_KKTCOMPL_MPCCcar	(MPCCcar_float)(1E-06)


/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_MPCCcar      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_MPCCcar (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_MPCCcar   (2)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_MPCCcar  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_MPCCcar   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_MPCCcar  (-6)

/* no progress in method possible */
#define NOPROGRESS_MPCCcar   (-7)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_MPCCcar   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_MPCCcar   (-12)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_MPCCcar  (-100)

/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)



/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 9 */
    MPCCcar_float xinit[9];

    /* vector of size 780 */
    MPCCcar_float x0[780];

    /* vector of size 3780 */
    MPCCcar_float all_parameters[3780];


} MPCCcar_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* vector of size 780 */
    MPCCcar_float all_var[780];


} MPCCcar_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* iteration number */
    solver_int32_default it;

	/* number of iterations needed to optimality (branch-and-bound) */
	solver_int32_default it2opt;
	
    /* inf-norm of equality constraint residuals */
    MPCCcar_float res_eq;
	
    /* inf-norm of inequality constraint residuals */
    MPCCcar_float res_ineq;

	/* norm of stationarity condition */
    MPCCcar_float rsnorm;

	/* max of all complementarity violations */
    MPCCcar_float rcompnorm;

    /* primal objective */
    MPCCcar_float pobj;	
	
    /* dual objective */
    MPCCcar_float dobj;	

    /* duality gap := pobj - dobj */
    MPCCcar_float dgap;		
	
    /* relative duality gap := |dgap / pobj | */
    MPCCcar_float rdgap;		

    /* duality measure */
    MPCCcar_float mu;

	/* duality measure (after affine step) */
    MPCCcar_float mu_aff;
	
    /* centering parameter */
    MPCCcar_float sigma;
	
    /* number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;
    
    /* number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;
    
    /* step size (affine direction) */
    MPCCcar_float step_aff;
    
    /* step size (combined direction) */
    MPCCcar_float step_cc;    

	/* solvertime */
	MPCCcar_float solvetime;   

	/* time spent in function evaluations */
	MPCCcar_float fevalstime;  


} MPCCcar_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Monday, February 1, 2021 9:26:36 PM */
/* User License expires on: (UTC) Monday, February 15, 2021 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Monday, February 15, 2021 10:00:00 PM (approx.) */
/* Solver Generation Request Id: 8273d0e0-2e7d-4904-a843-02163d85bfe6 */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef void (*MPCCcar_extfunc)(MPCCcar_float* x, MPCCcar_float* y, MPCCcar_float* lambda, MPCCcar_float* params, MPCCcar_float* pobj, MPCCcar_float* g, MPCCcar_float* c, MPCCcar_float* Jeq, MPCCcar_float* h, MPCCcar_float* Jineq, MPCCcar_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default MPCCcar_solve(MPCCcar_params *params, MPCCcar_output *output, MPCCcar_info *info, FILE *fs, MPCCcar_extfunc evalextfunctions_MPCCcar);	







#ifdef __cplusplus
}
#endif

#endif
